### ISSUE TITLE
Efficiency problem of assigning square blocks to the processors

### ISSUE THREAD

**Issue by trashcrash** [brower/EC526#10]
Hi, 

My "square" version is a little slower than my "strip" version. As the processor number increases (I tried 4 and 16), the time difference of the two becomes less obvious. In my code, there are more if-else's for the boundary and corner checks of each block, and the columns need more time to be sent and received because of the discontinuous memory addresses in columns. 

So my question is: Is it normal that the square version is slower? 

Thanks! 
Chunshu

**Comment by cpviolator** [comment]
This is known as a ‘surface to volume’ problem. The more surface (boundary)
there is in a given calculation, the more time is spent exchanging data.
All MPI communications come with some overhead. And, of course, while
communications are happening you can’t compute.

In a perfect world, using N processors would make your code N times faster.
This is known as ‘strong scaling.’ In the real world it’s never exactly N
times faster, it’s some number less than N. This is known as ‘strong
scaling violation’ and this is a major source of research in HPC. We always
want to minimize strong scaling violation.

In some calculations, strong scaling violations get so bad that we see very
little speed up.For example, I once used 256 GPUs on a big calculation, but
using 512 only made the calculation 1.1 times faster.

Google ‘strong scaling violation HPC’ to learn more.
