### ISSUE TITLE
L=1024

### ISSUE THREAD

**Issue by jimmykdunn** [brower/EC526#14]
Does "The number of grid points should be large so the linear dimension is at least L = 1024" mean that for our 2D multigrid code, that the grid should be a 1024-by-1024 grid, or does it mean that it should be a 32x32 grid (1024 total pixels)? 

I ask because a 1024x1024 grid takes a LONG time to run with Jacobi iterations (well more than an hour).

**Comment by brower** [comment]
I meant 1024x1024 but of course if this is too large for some reason  pick sizes that
are practical.

Have fun.

Rich
