### ISSUE TITLE
MakeACC is not parallelizing...

### ISSUE THREAD

**Issue by jimmykdunn** [brower/EC526#5]
I have a working makefile and program (in serial) for my test_integrate_feynman program.  I took the working makefile and simply replaced this line:

CCX = g++

with this line:

CCX = pgc++

I have appropriate acc pragmas in my code, but after doing make -k -f makeACC, the usual pgc++ detailed compilation log does not show up, and the code does not appear to actually be parallelized - runs at the same speed as serial.  Anyone else having this problem?

**Comment by cpviolator** [comment]
Can you please upload the `makeACC` file you're using? Have you included the proper flags?

`CXXFLAGS += -Minfo=accel -fast -acc -ta=tesla:cc60`

**Comment by jimmykdunn** [comment]
[makeACC.txt](https://github.com/brower/EC526/files/2916890/makeACC.txt)

**Comment by jimmykdunn** [comment]
-fast and -acc flags prevents compilation, I think because I'm using c++ and not c

**Comment by brower** [comment]
Ok Dean suggest another perhaps more likely problem?
Try changing to

CXX = pgc++

This might fix it. CXX is a standard token. 

Rich

**Comment by jimmykdunn** [comment]
Using CXX instead of CCX did the trick, thank you!  Strange that it matters...

**Comment by brower** [comment]
Not that it probalby really matters but a Makefile  should have .txt attribute.
To fallow conventions just call it:
makeACC

Cheers

Rich

**Comment by jimmykdunn** [comment]
I have it as "makeACC" in my HW4 folder on the SCC.  Github just wouldn't let me upload a file named "makeACC" because it has no extension, so I had to add ".txt" to make it happy.

**Comment by brower** [comment]
Ok. Software is full of weird surprises!  Any this "issue"  Github
messaging is fun and useful!

Cheers,

Rich
