### ISSUE TITLE
submit script error

### ISSUE THREAD

**Issue by jimmykdunn** [brower/EC526#9]
I have code that is working with mpirun when on an interactive node, but using one of the (slightly modified) example submit scripts, the job finishes with this in the output text file (repeated four times):

[proxy:0:0@scc-we4] HYDU_create_process (utils/launch/launch.c:75): execvp error on file ./jacobi_mp
i (No such file or directory)

I am running this from the same directory that my jacobi_mpi executable is located... confused why the submit script can't find it...

**Comment by cpviolator** [comment]
Can you upload the script? Also, can you run `module list` so we can see what your environment looks like?

**Comment by jimmykdunn** [comment]
#! /bin/bash -l
# The -l specifies that we are loading modules
#
## Walltime limit
#$ -l h_rt=0:10:00
#
## Give the job a name.
#$ -N jacobiMPI4
#
## Redirect error output to standard output
#$ -j y
#
## What project to use. "paralg" is the project for the class
#$ -P paralg
#
## Ask for nodes with 4 cores, 4 cores total (so 1 node)
#$ -pe mpi_4_tasks_per_node 4

# Want more flags? Look here:
# http://www.bu.edu/tech/support/research/system-usage/running-jobs/submitting-jobs/

# Load the correct modules
module load gcc/5.3.0  # compiler
module load mpich/3.2  # consistent mpi compile

# Immediately form fused output/error file, besides the one with the default name.
exec >  ${SGE_O_WORKDIR}/${JOB_NAME}-${JOB_ID}.scc.out 2>&1

# Invoke mpirun.
# SGE sets $NSLOTS as the total number of processors (8 for this example) 
mpirun -np $NSLOTS ./jacobi_mpi

exit

**Comment by cpviolator** [comment]
OK, the SCC is not the best at maintenance. Please adjust your environment to the following:

`module load gcc/7.2.0`
`module load mvapich2/2.3_gcc-7.2.0`

then recompile the executable. Also, change the module load  in the run script too.

Hint: when you print from an MPI program, make sure only the head node is printing:

```if (my_rank == 0) printf("N %d time_s %.10f\n", N, difference_in_seconds);```

**Comment by jimmykdunn** [comment]
Thanks! Will try this out later tonight/tomorrow and confirm it works for me as well.

**Comment by jimmykdunn** [comment]
So I loaded both the above modules, and did a "module list" to confirm that those modules and not the old ones are active.  Changed the submit script as well.  Still getting exactly the same error.

Are there maybe additional changes to the provided submit scripts needed to get this working via qsub?

**Comment by jimmykdunn** [comment]
Correction: almost the same error.  Appears to have pulled from the new module, but same error nonetheless:

HYDU_create_process (../../../../src/mvapich2-2.3/src/pm/hydra/utils/launch/laun
ch.c:75): [proxy:0:0@scc-ye4] execvp error on file ./jacobi_mpi (No such file or directory)

**Comment by jimmykdunn** [comment]
Figured it out: you have to _explicitly_ give your executable a path in the submit script since the qsubbed version will be running in some directory other than the HW5 directory.  In my case, I needed this:
mpirun -np $NSLOTS ${SGE_O_WORKDIR}/jacobi_mpi

instead of what the examples have:
mpirun -np $NSLOTS ./jacobi_mpi
